/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var n=Object.defineProperty;var s=Object.getOwnPropertyDescriptor;var l=Object.getOwnPropertyNames;var c=Object.prototype.hasOwnProperty;var m=(o,e)=>{for(var i in e)n(o,i,{get:e[i],enumerable:!0})},p=(o,e,i,d)=>{if(e&&typeof e=="object"||typeof e=="function")for(let t of l(e))!c.call(o,t)&&t!==i&&n(o,t,{get:()=>e[t],enumerable:!(d=s(e,t))||d.enumerable});return o};var f=o=>p(n({},"__esModule",{value:!0}),o);var u={};m(u,{default:()=>a});module.exports=f(u);var r=require("obsidian"),a=class extends r.Plugin{foldProperties(e){let i=activeDocument.querySelector(".workspace-leaf.mod-active");i&&(i.querySelector(".metadata-container.is-collapsed")||this.app.commands.executeCommandById("editor:toggle-fold-properties"))}async onload(){this.registerEvent(this.app.workspace.on("file-open",this.foldProperties.bind(this)))}};

/* nosourcemap */